### ISSUE TITLE
SSL for this CouchDB plugin

### ISSUE THREAD

**Issue by BigBlueHat** [dokku/dokku-couchdb#23]
First (and foremost!), thank you for building this plugin! 😺 

Second, I'm working to add HTTPS/SSL access to my installation of this plugin, and there seem to be two options:
1. add the certs to this plugin's container post installation
2. create an nginx reverse proxy app in front of this, and setup SSL in that layer

My use case is having multiple domains (currently via CouchDB's vhosts setup) mapped to a specific database within this container. The same could be possible via the nginx reverse proxy stuff, but I'm newer to nginx than CouchDB.

Ideally, I'd wrap all the fiddly bits in a bash script or something that would add the domain, create a letsencrypt cert, and install it in either of these containers (or somewhere else per dokku magic).

I'm still digging for answers, but if this is a thing this plugin could easily support (or assist with), that'd be super fabulous. 😸 

Much thanks!
🎩

**Comment by josegonzalez** [comment]
One way to do this with nginx is to use dynamic upstream backends in lua that would be resolved via the docker socket. Here is an example of doing so with [consul](https://medium.com/@sigil66/dynamic-nginx-upstreams-from-consul-via-lua-nginx-module-2bebc935989b). In this way, your lua bit would not need to know the container id - just the name alias we set - and you could use whatever cert you wanted.

Adding letsencrypt support directly to this plugin would - I think - be a bit aggressive for me to work on as OSS, but I would be happy to do the work if sponsored (feel free to reach out via email if you'd like to go down that route). Otherwise, I would also accept a pull request for this, but I don't think it's likely to get done otherwise.

Closing for now, but feel free to reach out via slack/email if you want further ideas on setting this up.
